[[main]]
name = "Arts"
pre = "apple"
pageRef = "arts"
identifier = "0hNWghTsJU"
weight = 2

[[main]]
name = "Maths"
pre = "star"
pageRef = "maths"
identifier = "y2je4uSTct"
weight = 1

[[main]]
name = "Muscis"
pre = "music"
pageRef = "musics"
identifier = "NvFM26xXzO"
weight = 3

[[footer]]
none = "none"

[[footer]]
name = "Maths"
pageRef = "maths"
identifier = "lX7MnqfLlq"
weight = 1

[[footer]]
name = "Arts"
pageRef = "arts"
identifier = "pk0NwDBo88"
weight = 2

[[footer]]
name = "Musics"
pageRef = "musics"
identifier = "wjnYhECvXG"
weight = 3
