name: Build and Deploy Hugo
on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持网页手动点击运行

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENVIRONMENT: production
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true # 如果你的主题是 git submodule 安装，这个必须开启

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest

      - name: Build static site
        run: hugo --minify

      - name: Upload site files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
